### PR TITLE
Guard against ActiveJob not being loaded

### PR DESCRIPTION
**Pull request by jeremyw**

### CODE REVIEW

**Comment by semanticart** [comment]
Ooh, thanks for the PR! This looks legit. 

For posterity, can you say more about how this was being loaded that caused trouble? Are you (e.g.) just not using ActiveJob?

**Comment by jdwyah** [comment]
yeah, `ActiveStorage` was for older rails. Is it wrong to just do this to all of them?

**Comment by jeremyw** [comment]
We use sidekiq but don't use activejob so we exclude it (and a few other things) from our application.rb requires to reduce our footprint. I think that's pretty common.

**Comment by semanticart** [comment]
That's for the color and the contribution! I'll merge this and cut a new version.

@jdwyah probably but I want to think some about how we can do that in a way that doesn't mean we're just silently doing nothing if this method is invoked at the wrong time. That might be as simple as erroring if _none_ of the things are defined but I'm guessing there's nuance.

**Review by semanticart — APPROVED** [review]

**Comment by semanticart** [comment]
I've released 0.23.7 to include your change. Thanks again and please reach out if there's anything we can do to help your prefab adoption go smoothly ❤️

**Pull request merged**
